# 使用openjdk作为基础镜像
FROM openjdk:17-jdk-alpine

# 设置工作目录
WORKDIR /app

# 复制打包好的JAR文件到容器中
COPY target/demo-0.0.1-SNAPSHOT.jar app.jar

# 暴露9091端口
EXPOSE 9091

# 启动Spring Boot应用
ENTRYPOINT ["java", "-jar", "app.jar"]
